services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_vol:/data/db      

  mongoimport:
    image: mongo
    volumes:
      - ./data:/data/db/vol
    command: mongorestore -u root -p example --authenticationDatabase admin -h mongo --port 27017 -d salaries /data/db/vol/sample_collection.bson
    depends_on:
      - mongo 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    depends_on:
      #- mongoimport
      mongoimport:
       condition: "service_completed_successfully"

  myapp:
    build: .
    command: bash -c "python main.py"
    depends_on:
      #- mongoimport
      mongoimport:
       condition: "service_completed_successfully"
    env_file:
      - .env

volumes:
  mongodb_vol: